Repository Zwater/Nixbot, pull requests merged in 2018-07, with the labels that each got.

#17 Minor changes to copypasta and join messages
  joinmessages.json
  plugins/copypasta/copypastas.json
Labels: bug

#16 Plugin conversion
  app.js
  modules/extraneous.js
  plugins/cowsay.py
  plugins/cowsay.sh
  plugins/fortune.py
  plugins/fortune.sh
  plugins/mymessages.py
  plugins/mymessages.sh
  plugins/plugins.json
  plugins/remember.py
  plugins/remember.sh
  plugins/test.py
  plugins/test.sh
  plugins/toilet.py
  plugins/toilet.sh
  plugins/wallit.py
  plugins/xkcd.py
  plugins/xkcd.sh
Labels: enhancement

#23 Event files
  .gitignore
  app.js
  events/guildCreate.js
  events/guildDelete.js
  events/guildMemberAdd.js
  events/message.js
  events/messageDelete.js
  events/messageUpdate.js
  events/ready.js
  modules/extraneous.js
  package.json
Labels: enhancement

#24 Bidoooooooooooooooooof
  Roblox_Death_Sound_Effect.mp3
  bidoof.png
  events/message.js
  plugins/mymessages.py
Labels: enhancement

#27 Sleep function fix
  events/message.js
Labels: fix

#29 Fixed error in regex that allowed 'bidof' to match
  events/message.js
Labels: fix

#30 Support no messages roles
  events/message.js
Labels: enhancement

#31 Event cleanup
  app.js
  events/message.js
  events/messageDelete.js
  events/messageUpdate.js
  modules/extraneous.js
  plugins/remember.py
Labels: cleanup
